spring:
  application:
    name: client
server:
  port: 8763

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/  # 有多少eureka-server填写多少地址
