spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: buzhidao
    url: jdbc:mysql://localhost:3306/FastSCService?characterEncoding=utf-8&useSSL=false
server:
  port: 8764

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/